version: '3.8'

services:
  core:
    container_name: nest-core
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - .:/srv/app/core
    ports:
      -  "3000:3000"
    networks:
      nest-basic-template:

  database:
    container_name: nest-database
    image: postgres:${DATABASE_VERSION}-alpine
    environment:
      POSTGRES_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../data/nest-basic-template/db/data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      nest-basic-template:    

networks:
  nest-basic-template:
    driver: bridge